### PR TITLE
complete: simple performance improvements (see #64)

### LINKED ISSUE #64: Pre-PR: [auto] completion performance improvements
Hi @akinomyoga :)

First, thank you for this software, it's very nice and useful, and BTW writing such a huge code base in pure bash and still manage to get it working properly is almost an artistic performance so congratulations xD.

I'm experiencing completion-related performance issues with `ble.sh`, both `v0.3.2` and d84bcd8 (master). For me, completion becomes very slow (and is thus unusable) in two specific situations: dynamic command completion with a very large number of candidates (12438), and filename completion in a directory containing a very large number of files (57341).

I'm currently trying to fix these two issues starting from d84bcd8 (master). I will submit a PR when I'm done. In the meantime I wanted to open this issue to get your feedback.

For now I'm focused on the second case only: filenames. After some digging, I think the performance bottleneck is, for this specific case, located on [this loop](https://github.com/akinomyoga/ble.sh/blob/d84bcd8/lib/core-complete.sh#L1765), on [that loop](https://github.com/akinomyoga/ble.sh/blob/d84bcd8/lib/core-complete.sh#L1771), and also [here](https://github.com/akinomyoga/ble.sh/blob/d84bcd8/lib/core-complete.sh#L1760).

Concerning the last line (pattern expansion), there is a huge performance regression in d84bcd8 (master) whereas on `v0.3.2` it's mostly fine: the generated pattern is simpler (and way faster) in `v0.3.2`.

I'm experimenting with two new options:
- `$bleopt_complete_max_precandidates` to abort completion as soon as we know that the number of candidates would be too high to be useful (right after pattern expansion). Then we could simply display "too much candidates". Fish is doing something similar.

- `$bleopt_complete_advanced_globbing` to switch to simpler/faster globbing patterns (it could also be something like `$bleopt_complete_globbing_type` to switch between a very simple pattern, the pattern of `v0.3.2`, and that of `master`).

Maybe this could also help with #58 and #59.

To be continued...

**EDIT** I forgot to mention that pattern expansion is only slow with `bleopt complete_ambiguous=1`. Still, I think it would be nice to provide a simpler pattern option for the ambiguous case (like `/*dir*/*file*` instead of `/*d*i*r*/*f*i*l*e*`).

### PR DESCRIPTION
**Pull request by timjrd**
This implements what was discussed in #64. I didn't implement a dedicated `substr` pattern for filenames because it would have required to significantly alter the `substr` filter and I wanted to keep this patch small. `complete_limit` is checked only in some cases, namely those where I was facing prohibitive processing time: I didn't want to add checks everywhere without testing them.

My Bash skills are rather limited and this project is fairly complex so please don't hesitate to ask me to fix this PR if necessary. Also, maybe this needs more testing: I'm switching my `ble.sh` installation to this branch.

Edit: Resolve #64

### CODE REVIEW

**Review by akinomyoga — COMMENTED** [review]
Thank you! Nice! I have a few discussions.

> complete_limit is checked only in some cases, namely those where I was facing prohibitive processing time: I didn't want to add checks everywhere without testing them.

OK. Actually, that was what I intended: we can add checks anytime later when we noticed some performance issues.

> My Bash skills are rather limited and this project is fairly complex so please don't hesitate to ask me to fix this PR if necessary.

Your code looks fine! It is not a matter of skill, but there are certain coding styles of `ble.sh` and also some bugs of old Bash. I will check for such trivial fixes after we settled the design for this new feature. For now, let us discuss the detailed behavior of the new option. I have several comments as will be written in the subsequent review comments. 

### blerc

I would appreciate it if you could add a description of the new option in [blerc template](https://github.com/timjrd/ble.sh/blob/complete-limit/blerc#L388).

### substr pattern

<details><summary>Outdated. Please forget about this discussion.</summary>

> I didn't implement a dedicated substr pattern for filenames because it would have required to significantly alter the substr filter and I wanted to keep this patch small.

I looked into the code, and now I see your point. The current `substr` filter is so general that it doesn't treat the path separator `/` in a special way. We might want some pattern like `*dir1*/*dir2*/*file*` for the path `dir1/dir2/file` , but the filter only accepts the pattern like `*dir1/dir2/file*`.

I thought of allowing the skip of filtering when the source itself does the filtering, but the current implementation in `ble.sh` is not so clean that it is possible. I think I later change to perform the filtering in `ble/complete/cand/yield` instead of after the call of sources, and then add the way to skip filtering.

~~For now, to match with the current behavior of `substr` filter, could you please just generate a pattern as ` ble/string#quote-word "$path"; local pattern=*$ret*` for `*:m:*`?~~ **Edit**: I have applied such a change in 7c6b67b along with other cleanups of filtering codes.

</details>

See updates in https://github.com/akinomyoga/ble.sh/pull/65#issuecomment-722807588 .

----

Thank you again for your PR!

File: lib/core-complete.sh [hunk 1]
```diff
@@ -4360,10 +4392,15 @@ function ble/widget/complete {
...
   fi
   if ((cand_count==0)); then
+    local complete_limit_reached=
     ble/complete/generate-candidates-from-opts "$opts"; local ext=$?
     if ((ext==148)); then
       return 148
-    elif ((ext!=0||cand_count==0)); then
+    fi
+    if [[ $complete_limit_reached ]]; then
+      ble/term/visible-bell "complete: limit reached"
```
Comment (akinomyoga) [inline lib/core-complete.sh:4401]: I would like to use `ble/widget/.bell` rather than the hardcoded `ble/term/visible-bell`. `ble/widget/.bell` is a configurable bell by the options `bleopt edit_vbell` and `bleopt edit_abell` (maybe it is quicker than words to see the actual implementation by `type ble/widget/.bell`).

Also, could you prepend `[[ :$opts: != *:no-bell:* ]] &&` before the bell similarly to the subsequent call of `ble/widget/.bell`. I would like to suppress the bell when the internal complete option `no-bell` is specified.

**Comment by akinomyoga** [comment]
I've tried. I'm thinking that we can change the limit for tab-completion and auto-completion, i.e., the latter is smaller than the former. What do you think?

For example, add `bleopt complete_limit_auto` for the latter. When `bleopt complete_limit_auto` is empty, the common setting `complete_limit` is used for auto-completions. It is cumbersome to write such a logic every time, so we can add the following utility and replace `[[ XXX -gt $bleopt_complete_limit ]]` by `! ble/complete/source/test-limit XXX`.

```diff
diff --git a/lib/core-complete.sh b/lib/core-complete.sh
index ee90fde..1ebeae6 100644
--- a/lib/core-complete.sh
+++ b/lib/core-complete.sh
@@ -1312,6 +1312,15 @@ function ble/complete/action:variable/init-menu-item {
 #------------------------------------------------------------------------------
 # source

+function ble/complete/source/test-limit {
+  local value=$1
+  local limit=$bleopt_complete_limit
+  [[ $bleopt_complete_limit_auto && :$comp_type: == *:auto:* ]] &&
+    limit=$bleopt_complete_limit_auto
+  ((limit=limit)) # evaluate arithmetic expression
+  ((limit<=0||value<=limit))
+}
+
 ## 関数 ble/complete/source/reduce-compv-for-ambiguous-match
 ##   曖昧補完の為に擬似的な COMPV と COMPS を生成・設定します。
 ##   @var[in,out] COMPS COMPV
```

**Comment by timjrd** [comment]
Hi! Sorry, I'm a bit busy right now, but I will take care of this and rework the patch in the next couple of weeks!

**Comment by akinomyoga** [comment]
@timjrd OK, thank you for letting me know that! Please take your time.

----

I have updates on `substr` filter for pathnames. In short, 1) I have cleaned up the filtering code in 7c6b67b (There is no conflict with this PR). 2) I won't support `substr` filter like `*dir1*/*dir2*/*file*` but just `*dir1/dir2/file*`. More flexible matching should be achieved in the subsequent `hsubseq` / `subseq` filter. I added the corresponding glob pattern specialized to `substr` for `source:file` ([here](https://github.com/akinomyoga/ble.sh/commit/7c6b67be0212a81a26aa3f42f581e372a55370cb#diff-c180d07f9f6314cd0ce60494fd95e4a1a3afaa2f78afd7046897c4c4e6f072d3R1712)).

<details>
<summary>If you are interested in the reasons, here is the detail.</summary>

- In the first review comment, I wrote that the current `ble.sh` implementation of the filter is not clean, but now I cleaned up the codes in the latest commit 7c6b67b. Previously, the filter is performed on the candidate list after the source added all the candidates in the list. Now, the filter is performed in `ble/complete/cand/yield` which is called inside the source, so that the candidates that don't match the condition are not added in the list from the beginning.
- I decided not to support the special filter of the form `substr` like `*dir1*/*dir2*/*file*` as your decision. The reason is that the filtering rule becomes inconsistent when several sources produce the candidates with different rules. When there are several viable candidates, the inserted text will be the common prefix or common subsequence, but when there are candidates of different filtering rules, the common subsequence rule becomes non-trivial. This is not only tricky to implement but also not user-friendly. So I will not support `*dir1*/*dir2*/*file*`.
</details>

File: lib/core-complete.sh [hunk 2]
```diff
@@ -2483,6 +2509,7 @@ function ble/complete/source:argument {
       local ret cand
       ble/complete/source:file/.construct-pathname-pattern "$value"
       ble/complete/util/eval-pathname-expansion "$ret"
+
```
[the remark this answers is not in the document]
Comment (akinomyoga) [reply lib/core-complete.sh:2512]: I've pushed new commits for #67. There is a conflict for this empty line. The conflict should be resolved by just removing this empty-line insertion.

**Comment by timjrd** [comment]
Hi! Here is the patch reworked according to your comments.

In the meantime I switched to infinite Bash history and after some time auto-completion became very slow, I thought I could add a limit check inside the history source, especially since other users are experiencing issues with big histories. I also faced huge slowdowns with completion on paths containing wildcards. I will try to address these two issues when I have some time, but I need to reproduce them reliably first. Maybe this would be a better fit for another PR.

Concerning the visual bell, it's not a big deal, but do you think it would be possible to display the message `limit reached` in place of the completion candidates (below the prompt)?

Thanks!

**Comment by akinomyoga** [comment]
Nice! Thank you!

> In the meantime I switched to infinite Bash history and after some time auto-completion became very slow, [...] Maybe this would be a better fit for another PR.

I think they can be discussed in separate PRs. Let's first settle this PR, and then you can make another PR/PRs.

> after some time auto-completion became very slow, I thought I could add a limit check inside the history source

May I ask in detail? In what sense it is slow?
- Does the response to the user input become slow? The auto-complete is designed not to block the user-input processing in the current implementations, so if `auto-complete` makes the response to the user input slow, that is the bug of the user input detection. So the fix should be made in that detection rather than by limiting the number of candidates.
- Or, does the time until a suggestion become longer? In this case, canceling auto-complete is effectively equivalent to make the time infinite in the sense of slowness, so I don't think adding a limit check in the history source improves the user experience. Maybe canceling the history-based auto-complete early and falling to the normal word-by-word auto-complete would make the waiting time faster, but I actually don't want to break the reproducibility of the auto-complete results by unpredictable conditions. Though this does not affect the user experience, another problem might be again the CPU usage.

> especially since other users are experiencing issues with big histories.

I actually doubt if his problem is really related to the big history. As already written, the history-based completion is designed not to block the user input, i.e., the processing will be immediately canceled when there is user input, so I don't have an idea what happened there. Then he didn't respond after that, so there was no chance to get a hint on the problem. Usually, the initial guess of users (who didn't really look into the code) is wrong (or, in other words, mostly random) to my experience. In particular, a large history is a popular naive guess in the past issues actually.

### Re: Limit reached message

> Concerning the visual bell, it's not a big deal, but do you think it would be possible to display the message limit reached in place of the completion candidates (below the prompt)?

Yes, it is possible. Actually, I was also thinking a similar idea. You can use the function `ble-edit/info/show` to put the message below the command line. For example, you can use the following command.

```bash
ble-edit/info/show ansi $'\e[38;5;242m(too many completions)\e[m'
```

But, here we need to carefully design the behavior because the limit check is performed for each source which means that, even when some source reached the limit, another source might still generate candidates. In that case, both the message and the completions cannot be shown in the same place at the same time.

For example, how about showing the message below the command line only when there are no completions at all, or otherwise ringing bells?

File: lib/core-complete.sh [hunk 3]
```diff
@@ -1602,6 +1622,8 @@ function ble/complete/source:command {
   [[ $compgen ]] || return 1
   ble/util/assign-array arr 'ble/bin/sort -u <<< "$compgen"' # 1 fork/exec
 
+  ble/complete/source/limit arr
```
Comment (akinomyoga) [inline lib/core-complete.sh:1625]: I think, when it reaches the limit, one can soon exit the function rather than proceeding with the subsequent steps with an empty array. Canceling the processing is logically more natural than proceeding with the empty array.

File: lib/core-complete.sh [hunk 4]
```diff
@@ -1661,6 +1683,8 @@ function ble/complete/util/eval-pathname-expansion {
   IFS= GLOBIGNORE= builtin eval "ret=(); ret=($pattern)" 2>/dev/null
 
   ble/util/invoke-hook dtor
+
+  ble/complete/source/limit ret
```
Comment (akinomyoga) [inline lib/core-complete.sh:1687]: Can you change to exit with non-zero status keeping the results of the pathname expansion, and checks the exit status at the caller side to let the caller decide whether to cancel the processing or not?

File: lib/core-complete.sh [hunk 5]
```diff
@@ -2352,6 +2376,8 @@ function ble/complete/progcomp/.compgen {
     fi
   } 2>/dev/null
 
+  ble/complete/source/limit arr
```
Comment (akinomyoga) [inline lib/core-complete.sh:2379]: the same as above

File: lib/core-complete.sh [hunk 6]
```diff
@@ -2823,6 +2849,8 @@ function ble/complete/source/compgen {
   local arr
   ble/util/assign-array arr 'builtin compgen -A "$compgen_action" -- "$compv_quoted"'
 
+  ble/complete/source/limit arr
```
Comment (akinomyoga) [inline lib/core-complete.sh:2852]: the same as above

File: lib/core-complete.sh (hunk 3 above)
Comment (timjrd) [reply lib/core-complete.sh:1625]: The advantage of emptying the array is that it's not intrusive at all: the check is just a single line that we can insert each time it's needed without worrying too much. IMO early returns bring new code paths (and potentially bugs) as they require handling of exit codes all along the call chain.

File: lib/core-complete.sh (hunk 4 above)
Comment (timjrd) [reply lib/core-complete.sh:1687]: ok!

**Comment by timjrd** [comment]
Hi!

> May I ask in detail? In what sense it is slow?

I'm pretty sure that the slowdowns was caused by the Bash option `HISTCONTROL=erasedups`. But I can easily live without it. There is also a problem with completion on paths with glob patterns but I will open a specific issue.

> For example, how about showing the message below the command line only when there are no completions at all, or otherwise ringing bells?

Sounds fine!

File: lib/core-complete.sh (hunk 3 above)
Comment (akinomyoga) [reply lib/core-complete.sh:1625]: Thank you! I think it's a matter of taste. but I'd like to maintain the code to be faithful to the idea behind it rather than make the possible future modification easier (such as single-line insertion).

If I correctly understand what is meant by *intrusive*, I think whether it is intrusive or not, in this case, depends on the point of view. Actually, in my mind, the array belongs to the caller function so modifying it inside `ble/complete/source/limit` seems intrusive to me. Also, with this design of `ble/complete/source/limit`, it can only be used when the candidates are stored in arrays. There can be a case that the number of possible candidates is available in advance before the candidates are actually generated and stored in an array, where one wants to test the limit before the actual candidate generation. I thought the helper function should be independent of the implementation detail of the caller function, which is the reason why I let `ble/complete/source/test-limit` in https://github.com/akinomyoga/ble.sh/pull/65#issuecomment-720229429 receive a number (to which the caller can pass the number of array elements or any other values).

As for the early return, it is again a matter of taste, but whether early return should be used or not depends on the case. I can understand that, by refraining from early returns and suppressing the number of code paths, certain types of bugs can be avoided, but there are instead bugs caused by not reducing the problem interest. In fact, in the current PR, `ble/complete/source:command` doesn't correctly return `1` when it surpassed the limit, which is a consequence of handling different cases into a branch. When early returns are not used, one needs to care about all the exceptional cases in modifying any part of the functions.

I'm actually highly skeptical of cyclomatic complexity or alike. It does extract some aspects of the code, but it's not everything that determines the readability or maintainability. Anyway, there are certain cases that I'll absolutely use early returns. In particular, I'll use early returns for error/exceptional cases, and this complete limit check fits this pattern.

Exit code handling is intended design and unrelated to the early returns. Even without early returns, I would request to properly handle exit codes.

**Comment by akinomyoga** [comment]
> the slowdowns were caused by the Bash option `HISTCONTROL=erasedups`

OK! I think this causes the slowdown when a command is executed and thus added to the command history, but does it cause the slowdown to `auto-complete`? I'm going to test it in detail.

> There is however a performance problem with completion on paths with glob patterns but I will open a dedicated issue for that.

OK!

> Sounds fine!

Thank you! Then, you can switch to `ble-edit/info/show` (as described in https://github.com/akinomyoga/ble.sh/pull/65#issuecomment-735523487) when `cand_count == 0`!

**Comment by timjrd** [comment]
Hi! Here is the patch reworked with exit codes. I tried to use `ble-edit/info/show`, but `cand_count` is not always zero even if there are no candidates so I left the code with the bell as-is. Thanks.

**Comment by akinomyoga** [comment]
Thank you!

May I ask if you have diff between the previous patch and the current patch? Since the changes are squashed (or the commit is directly amended), it is cumbersome to track what has been updated since the previous patch. I would like to avoid reviewing the same code from the beginning many times. Of course, I can still create temporary two branches on a certain commit at my local repository, cherry-pick both the previous and current patches on each branch and perform `diff` to see what has been changed, but I'm lazy to do that every time. So, if you don't have specific reasons to squash the changes for every update of the PR, I'll be happy if, from the next time, commits for incremental changes are just added. (BTW, rebasing and conflict resolution are welcome, unlike the squashing.) We can squash all the commits just before the merge :)

Anyway this time I'll make `diff` at my side

**Comment by akinomyoga** [comment]
> but cand_count is not always zero even if there are no candidates so I left the code with the bell as-is.

For example, `cand_count == 0` can be reproduced with the following commandline edit:

```bash
$ bleopt complete_limit=5 complete_ambiguous=
$ h[TAB]
```

Now I tried the suggested behavior with the following change, but it seems the behavior is a bit unnatural in vim mode. Actually, the line below the commandline is used for various purposes including the completion menu, current editing modes (various maps in vim / MULTILINE in emacs), error messages, etc. If the completion sets the error message, this message `(too many completions)`, which hides the other information, remains all along while the user inputs additional texts until the next completion.

```diff
diff --git a/lib/core-complete.sh b/lib/core-complete.sh
index e9f311c..c7d8931 100644
--- a/lib/core-complete.sh
+++ b/lib/core-complete.sh
@@ -4804,17 +4804,21 @@ function ble/widget/complete {
     ble/complete/generate-candidates-from-opts "$opts"; local ext=$?
     if ((ext==148)); then
       return 148
-    fi
+    elif ((ext!=0||cand_count==0)); then
       if [[ $complete_limit_reached ]]; then
+        ble-edit/info/show ansi $'\e[38;5;242m(too many completions)\e[m'
+      else
         [[ :$opts: != *:no-bell:* ]] &&
-        ble/widget/.bell 'complete: limit reached'
-    fi
-    if ((ext!=0||cand_count==0)); then
-      [[ :$opts: != *:no-bell:* && -z $complete_limit_reached ]] &&
           ble/widget/.bell 'complete: no completions'
         ble-edit/info/clear
+      fi
       return 1
     fi
+
+    if [[ $complete_limit_reached ]]; then
+      [[ :$opts: != *:no-bell:* ]] &&
+        ble/widget/.bell 'complete: limit reached'
+    fi
   fi

   if [[ :$opts: == *:insert_common:* ]]; then
```

So, now I think we don't have to support the special treatment using `ble-edit/info/show`.

**Comment by akinomyoga** [comment]
I think it's almost done! The remaining are just trivial fixes and cosmetic changes.

- In the function `ble/complete/auto-complete/.check-context`,   https://github.com/akinomyoga/ble.sh/blob/1a4f87e51164c7543aed32e4d924aa49ebe0ad0e/lib/core-complete.sh#L5361-L5365 The local variable `complete_limit_reached` is leaked here, i.e., the global variable named `complete_limit_reached` would be created and changed while `auto-complete`. Can you add the following line just before the call of `ble/complete/candidates/generate` to correctly limit the scope inside `ble.sh`?

  ```bash
  local complete_limit_reached=
  ```

- To make it clear that the variable `complete_limit_reached` can be modified in the function, can you add the following line in the function descriptions?

  ```bash
  ##   @var[in,out] complete_limit_reached
  ```

  The corresponding functions are:

  https://github.com/akinomyoga/ble.sh/blob/1a4f87e51164c7543aed32e4d924aa49ebe0ad0e/lib/core-complete.sh#L3549-L3558
  https://github.com/akinomyoga/ble.sh/blob/1a4f87e51164c7543aed32e4d924aa49ebe0ad0e/lib/core-complete.sh#L4070-L4075

- We can also add the same line to the following description.

  https://github.com/akinomyoga/ble.sh/blob/1a4f87e51164c7543aed32e4d924aa49ebe0ad0e/lib/core-complete.sh#L1420-L1431

  Now I think we can also list other `cand_*` variables here, so can you add the following comments to the above code section?

  ```bash
  ##   @var[in,out] cand_count cand_cand cand_word cand_pack
  ##   @var[in,out] complete_limit_reached
  ```

- I thought maybe it's better to rename `complete_limit_reached` to `cand_limit_reached` because the scope and usage of the variable is similar to the other `cand_*` variables. What do you think of this idea?

- This is just a coding style, but in the following section, could you use `[[ ! ..... ]]` instead of `[[ -z ..... ]]`? https://github.com/akinomyoga/ble.sh/blob/1a4f87e51164c7543aed32e4d924aa49ebe0ad0e/lib/core-complete.sh#L4812-L4815

**Comment by akinomyoga** [comment]
Hi! How are you doing? It's not in a rush, but do you have a plan to finalize this PR? If you have already lost interest in this PR, I'm ready to continue finalizing the PR at my side (yet it seems the remaining fixes are rather trivial ones) :) Or, if you are just busy recently, I would appreciate it if you could just tell me that you are busy. Again, It's not in a rush, so I can wait as far as you don't lose interest! Thank you!

**Comment by timjrd** [comment]
Hi! Sorry for the delay, I must admit I was a bit busy (and also a bit lazy 😅). I will finalise the PR this weekend!

**Comment by akinomyoga** [comment]
OK! Thank you for your quick response!

**Comment by timjrd** [comment]
Hi :) Here are the remaining fixes. Thanks!

**Comment by akinomyoga** [comment]
Thank you! Looks fine! I merge it.

**Comment by akinomyoga** [comment]
Thank you so much for all the discussion and your work! I have merged the commit. I closed Issue #64 with this PR. If you think we need further discussion in #64 for another possible PR, please feel free to reopen it. I also added related descriptions to the manual ([`bleopt complete_limit`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-complete_limit) and [`bleopt complete_limit_auto`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A77-Completion#user-content-bleopt-complete_limit_auto)).

If you are willing in the future to discuss another performance improvement that you have mentioned in the following comment, I am always welcome!

>https://github.com/akinomyoga/ble.sh/pull/65#issuecomment-735314088
>
> In the meantime I switched to infinite Bash history and after some time auto-completion became very slow, I thought I could add a limit check inside the history source, especially since other users are experiencing issues with big histories. I also faced huge slowdowns with completion on paths containing wildcards. I will try to address these two issues when I have some time, but I need to reproduce them reliably first. Maybe this would be a better fit for another PR.

Thanks again for your work!

**Comment by timjrd** [comment]
I hope this tiny feature will prove useful :). Thanks for your time and for your help!

**Comment by akinomyoga** [comment]
Hi @timjrd. Recently, based on detailed reports in #82 by @3ximus, I have been adding a number of optimizations to completion and highlighting, which I think have some overlaps with your contributions. Today I pushed them to the `master` branch.

Now I think the user experience became much more responsive than before, so I'm thinking of increasing the default limit values for `complete_limit{,_auto}` that you introduced. If you have any thoughts, please let me know! (Actually, I'm not sure if these recent optimizations improve the performance issue you had. If not, maybe the default limit values should be kept as is.) Thank you!

**Comment by timjrd** [comment]
Hi! Sorry for the delay. I just tested revision `aae553c` (current master, with `complete_limit` set to infinity). In my case Bash is still frozen for a couple of seconds when attempting tab-completion on a very large directory.

**Comment by timjrd** [comment]
I tried to re-enable `complete_limit` but it doesn't seem to work anymore. If you would like to reproduce my issue, you could create say 20k empty directories + 20k empty files under the same directory and attempt a tab-completion on it. I must acknowledge that it's a quite unusual use case, so I can totally understand the slowdown. 

(unrelated, but this latest version doesn't work with the Kitty terminal emulator (seems to work fine with gnome-terminal though))

**Comment by akinomyoga** [comment]
Thank you for the feedback!

> In my case Bash is still frozen for a couple of seconds 

Does it mean the shell doesn't respond soon when the user supplies additional inputs while TAB completion? If the user doesn't input anything while the TAB completion, `ble.sh` continues the processing which is the intended behavior.

**Comment by akinomyoga** [comment]
> If you would like to reproduce my issue, you could create say 20k empty directories + 20k empty files under the same directory and attempt a tab-completion on it.

OK, I could reproduce it. By the way, what is your operating system? I reproduced it with Linux (Fedora).

> (unrelated, but this latest version doesn't work with the Kitty terminal emulator (seems to work fine with gnome-terminal though))

Thank you for the report. It seems there is a Linux version of Kitty, so I think I'll try it later.

**Comment by timjrd** [comment]
> Does it mean the shell doesn't respond soon when the user supplies additional inputs while TAB completion? If the user doesn't input anything while the TAB completion, `ble.sh` continues the processing which is the intended behavior.

For my use case, that's mostly the same problem as before: when I attempt a tab-completion a my very large directory, Bash is maxing up one CPU core for 10+ seconds. When I want to type something, the completion is correctly interrupted, but sometimes it takes a few seconds to respond.

> OK, I could reproduce it. By the way, what is your operating system? I reproduced it with Linux (Fedora).

I'm using Linux too, with an ext4 filesystem, and Bash 5. I'm using the NixOS distribution which is why I have to deal with a huge directory (the Nix store, ~40k entries on my system).

**Comment by akinomyoga** [comment]
In the previous commit, I wrote I could reproduce it, but possibly it was a different issue...

In my case, the problem has occurred in [some loops inside an old version of `bash-completion`](https://github.com/scop/bash-completion/blob/cefd0daf30e7022bdbce98de88dca5ba6244c1a5/bash_completion#L559-L561). In the loop, `bash-completion` uses the command `read` which is overwritten by `ble.sh`. `ble.sh` overwrites `read` to emulate `read -e` because `builtin read -e` doesn't work when `ble.sh` is enabled and readline is disabled. This `ble.sh` version of `read` is slower than the original Bash builtin which produced a visible difference on huge directories. However, these loops in `_filedir` were removed by the pull request https://github.com/scop/bash-completion/pull/205 on 2018-04. There are still a few similar loops in `_filedir_xspec`. For this issue, I'll later add workarounds.

May I ask questions to check whether your performance issue is related to the above one or not?

- Q1. Does it still reproduce after running `complete -r`?
- Q2. If the answer to Q1 is yes, what is the version of your `bash-completion`? The version of `bash-completion` is stored in the array `BASH_COMPLETION_VERSINFO`. You can check it by `declare -p BASH_COMPLETION_VERSINFO`.
- Q3. Does the performance issue occur with common commands such as the `echo` command or occur only with some special commands?

**Comment by akinomyoga** [comment]
I pushed some fixes to `master`.

In commit 856cec2, I fixed the issue I mentioned in the previous reply. To stop the loops (`while read ...`) inside `bash-completion`, I hooked `read` to check user inputs and `complete_limit_{,auto}`.

> (unrelated, but this latest version doesn't work with the Kitty terminal emulator (seems to work fine with gnome-terminal though))

In commit eca2976, I slightly changed the escape sequence so that Kitty can recognize it. Kitty doesn't recognize `DECSTBM` (<kbd>CSI <i>line</i> ; <i>col</i> r</kbd>) when *line* and *col* are empty. I switched to use <kbd>CSI r</kbd> which Kitty seems to understand (Actually, the behavior of Kitty is often strange).

**Comment by timjrd** [comment]
Hi! Thanks a lot for these fixes!

The following tests were done on `master` (`c8e658e`):

>     * Q1. Does it still reproduce after running `complete -r`? (Note: `complete -r` removes all the programmable completion settings in the current session).

Yes. Same thing.
 
>     * Q2. If the answer to Q1 is yes, what is the version of your `bash-completion`? The version of `bash-completion` is stored in the array `BASH_COMPLETION_VERSINFO`. You can check it by `declare -p BASH_COMPLETION_VERSINFO`.

```
$ declare -p BASH_COMPLETION_VERSINFO
declare -a BASH_COMPLETION_VERSINFO=([0]="2" [1]="10")
```

>     * Q3. Does the performance issue occur with common commands such as the `echo` command or occur only with some special commands?

Same thing with `echo`.

**Comment by akinomyoga** [comment]
OK! Thank you for testing! There seems to be still the performance issue even with the latest version in your environment. Actually, now I cannot reproduce the problem in my environment. For example, it works smoothly with the following command line:

```bash
$ mkdir {00000..19999}
$ touch {00000..19999}.txt
$ echo 012345
```

- I'm using two Fedora 30 systems where the main filesystem is XFS. I also tried Ubuntu 18 in VirtualBox where the filesystem is ext4. In these environments, I don't see a significant delay in quick testing.
- I also tried Arch Linux in VirtualBox where the filesystem is ext4. In this system, I observed a slight delay (about 0.5s in my feeling) in the working directory with 100k files and 100k directories.

You have told me that it sometimes takes a few seconds (as quoted below), but can you tell roughly how often it happens?

> When I want to type something, the completion is correctly interrupted, but sometimes it takes a few seconds to respond.

Have you experienced the delay in more than one NixOS system? If it consistently reproduces in multiple NixOS hosts, maybe I can set up my own NixOS distribution in my VirtualBox.

**Comment by timjrd** [comment]
Did you try:
```
$ mkdir {00000..19999}
$ touch {00000..19999}.txt
$ echo <TAB-TAB>
```
Without any prefix?

**Comment by akinomyoga** [comment]
OK, thank you for the information. I could reproduce it with 100k files + 100k directories and a certain interval between `<TAB-TAB>` and a user interruption. I'll later take a look.

**Comment by timjrd** [comment]
I guess you have a NVMe SSD and a beefier CPU, or maybe XFS is doing a better job here xD

**Comment by akinomyoga** [comment]
I found one bottleneck, but there are also several suspicious places. The processing speed of these suspicious places are not so bad in my environment, but they might be slow in your environment. Could you provide me the result of the following commands in normal Bash (i.e., with `ble.sh` detached) in your environment?

```bash
$ cd /path/to/big-directory
$ time files=(*)
$ time def=$(declare -p files)
$ time def=ret=${def#*=}
$ time eval "$def"
```

**Comment by timjrd** [comment]
Here you go:

```
$ echo $BASH_VERSION
5.0.17(1)-release

$ time files=(*)
real 0m0.063s
user 0m0.042s
sys 0m0.020s

$ time def=$(declare -p files)
real 0m0.046s
user 0m0.031s
sys 0m0.017s

$ time def=ret=${def#*=}
real 0m0.026s
user 0m0.018s
sys 0m0.009s

$ time eval "$def"
real 0m0.879s
user 0m0.845s
sys 0m0.034s

$ echo ${#ret[@]}
33800

$ time def="ret=(${files[*]@Q})"
real 0m0.093s
user 0m0.082s
sys 0m0.011s
```

**Comment by akinomyoga** [comment]
@timjrd Thank you for your results, and sorry for the long blank. After various experiments, I finally added another performance improvement in c89aa23.

Thanks to your measurement, the following part turned out to have a significant delay (which was actually not so slow in my system with 100k elements).

> ```bash
> $ time eval "$def"
> real 0m0.879s
> user 0m0.845s
> sys 0m0.034s
> ```

A similar operation has been used in `ble.sh` to transfer the filename list from a subshell to the parent shell. I was thinking about a more efficient way to transfer a very large filename list. I tried several different implementations (tested with 500k-element arrays) and finally chose to parse the result of `declare -p files` using `awk` in the subshell and load the results using `mapfile` in the parent shell.

Hope it could improve the situation in

> ```bash
> $ mkdir {00000..19999}
> $ touch {00000..19999}.txt
> $ echo <TAB-TAB>
> ```
>
> Without any prefix?
